# Generated by Django 4.1.7 on 2023-03-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_resources_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
